### ISSUE TITLE
Typing 'roo' into the search field breaks it

### ISSUE THREAD

**Issue by Nytra** [Banane9/NeosComponentAttacherSearch#1]
When you do this you will need to destroy the component attacher and spawn another one to be able to use the attacher again

**Comment by Banane9** [comment]
This was caused by it matching `<root>` as the name of the root node, which has a path of `/` - but I wasn't specifically handling that with the removing the initial `/` code, so it triggered an Exception as the code was trying to use everything behind the first character... which was also the only one.

**Comment by Nytra** [comment]
Thank you!
